name: eventos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0 # Ajusté esto a una versión estándar reciente, si te da error pon 3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- TUS DEPENDENCIAS DE FIREBASE (Están OK) ---
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  
  # --- LO QUE FALTABA (Login Google + Fechas) ---
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- CONFIGURACIÓN DE IMÁGENES ---
  # Es vital que respetes los espacios (identación) aquí abajo:
  assets:
    - assets/images/